apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
  labels:
    app: nginx
spec:
  replicas: 3
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        image: nginx:1.15.4
        ports:
        - containerPort: 80
service:
  type : NodePort
  ports : [
    {
      name: http,
      port: 80,
      protocol: TCP,
      targetPort: 80,
      nodePort:
    }
  ]
